import { useState } from 'react';
import ToolLayout, { CopyButton } from '../ui/ToolLayout';
import CodeEditor from '../ui/Editor';
import { FileJson, Settings, Code2 } from 'lucide-react';

export default function JsonToGo() {
  const [input, setInput] = useState('{\n  "id": 1,\n  "name": "Service Config",\n  "version": "1.0",\n  "active": true,\n  "metadata": {\n    "created_at": "2024-01-01T12:00:00Z",\n    "tags": ["prod", "api"]\n  },\n  "endpoints": [\n    {\n      "path": "/health",\n      "method": "GET",\n      "timeout": 30\n    }\n  ]\n}');
  const [output, setOutput] = useState('');
  const [rootName, setRootName] = useState('Configuration');

  const capitalize = (s: string) => {
    return s.split(/[^a-zA-Z0-9]/).map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
  };

  const generate = () => {
    if (!input.trim()) return;

    try {
      const obj = JSON.parse(input);
      const structs: string[] = [];
      const seenNames = new Set<string>();

      const getType = (val: any, key: string): string => {
        if (val === null) return 'interface{}';
        
        switch (typeof val) {
          case 'string': return 'string';
          case 'number': return Number.isInteger(val) ? 'int' : 'float64';
          case 'boolean': return 'bool';
          case 'object':
            if (Array.isArray(val)) {
              if (val.length === 0) return '[]interface{}';
              const first = val[0];
              const typeName = capitalize(key.replace(/s$/, '')) || 'Item';
              return `[]${getType(first, typeName)}`;
            }
            const name = capitalize(key) || 'SubStruct';
            return processObject(val, name);
          default: return 'interface{}';
        }
      };

      const processObject = (val: any, name: string): string => {
        // Ensure unique struct names
        let uniqueName = name;
        if (seenNames.has(uniqueName)) {
           let counter = 1;
           while (seenNames.has(`${uniqueName}${counter}`)) counter++;
           uniqueName = `${uniqueName}${counter}`;
        }
        seenNames.add(uniqueName);

        let fields = `type ${uniqueName} struct {\n`;
        for (const [k, v] of Object.entries(val)) {
          const goName = capitalize(k);
          const goType = getType(v, k);
          fields += `\t${goName} ${goType} \`json:"${k}"\`\n`;
        }
        fields += '}';
        
        structs.push(fields);
        return uniqueName;
      };

      processObject(obj, rootName);
      setOutput(structs.reverse().join('\n\n'));
    } catch (e) {
      setOutput('Error: Invalid JSON input');
    }
  };

  return (
    <ToolLayout
      title="JSON to Go Struct"
      description="Convert JSON data into idiomatic Go structs with JSON tags."
      onClear={() => { setInput(''); setOutput(''); }}
      actions={
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 bg-bg-header border border-border-main rounded-lg px-3 py-1.5">
            <Code2 size={12} className="text-text-secondary" />
            <input 
              type="text" 
              value={rootName}
              onChange={(e) => setRootName(e.target.value || 'AutoGenerated')}
              placeholder="Root Struct Name"
              className="bg-transparent text-[10px] text-text-main outline-none w-32 font-mono"
            />
          </div>
          <button 
            onClick={generate}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-brand hover:bg-brand/90 text-white text-xs font-bold transition-all shadow-lg shadow-brand/20 active:scale-95"
          >
            Generate
          </button>
          <CopyButton text={output} />
        </div>
      }
    >
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-full min-h-0">
        <div className="flex flex-col gap-4 h-full min-h-0">
          <div className="flex items-center justify-between px-1">
            <div className="flex items-center gap-2">
              <FileJson size={14} className="text-brand" />
              <label className="text-[10px] font-bold text-text-secondary uppercase tracking-widest">JSON Input</label>
            </div>
          </div>
          <div className="flex-1 min-h-0 rounded-2xl border border-border-main overflow-hidden bg-bg-editor">
            <CodeEditor
              value={input}
              onChange={setInput}
              language="json"
              placeholder="Paste JSON here..."
            />
          </div>
        </div>

        <div className="flex flex-col gap-4 h-full min-h-0">
          <div className="flex items-center justify-between px-1">
            <div className="flex items-center gap-2">
              <Settings size={14} className="text-brand" />
              <label className="text-[10px] font-bold text-text-secondary uppercase tracking-widest">Go Struct Definitions</label>
            </div>
            <div className="text-[10px] font-mono text-brand bg-brand/5 px-2 py-0.5 rounded border border-brand/20">
              go
            </div>
          </div>
          <div className="flex-1 min-h-0 rounded-2xl border border-border-main overflow-hidden bg-bg-editor">
            <CodeEditor
              value={output}
              onChange={() => {}}
              language="go"
              readOnly
              placeholder="Generated Go structs will appear here..."
            />
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
